spring.datasource.url=jdbc:postgresql://localhost:5433/pharmastock
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=VOTRE_MOT_DE_PASSE
spring.h2.console.enabled=false
spring.jpa.hibernate.ddl-auto=update
server.port=8080
jwt.secret=pharmastockSecretKey2026
jwt.expiration=86400000